# Generated by Django 4.1.3 on 2022-12-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLOL', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
