# Generated by Django 4.1.3 on 2022-11-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLOL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERSONAJES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeon', models.CharField(max_length=40)),
                ('buffonerfeo', models.DateField()),
                ('modificaciones', models.IntegerField()),
            ],
        ),
    ]
