# Generated by Django 4.1.3 on 2022-12-15 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppLOL', '0002_post_slug_alter_post_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comunidad',
            new_name='Campeones',
        ),
    ]
